
#Game Settings
FPS=32
SCREENWIDTH = 289
SCREENHEIGHT = 511
GROUNDY = SCREENHEIGHT * 0.8

#Player physics constants
PLAYER_START_X=int(SCREENWIDTH/5)
PLAYER_START_Y=int(SCREENHEIGHT/2)

PLAYER_VELOCITY_Y=-9
PLAYER_MAX_VELOCITY_Y=10
PLAYER_MIN_VELOCITY_Y=-8
PLAYER_ACC_Y=1
PLAYER_FLAP_ACC_V=-8

PIPE_VELOCITY_X=-4
